[project]
name = "magboltz-gui"
version = "0.3.0"
description = "Magboltz GUI - a GUI for Magboltz"
readme = "README.md"
requires-python = ">=3.12"

authors = [
  { name = "Michele Renda", email = "michele.renda@cern.ch" },
  { name = "Dan Andrei Ciubotaru", email = "dan.andrei.ciubotaru@cern.ch" }
]
dependencies = [
    "matplotlib>=3.10.7",
    "typing-extensions>=4.15.0",
]

[project.optional-dependencies]
qt = [
  "PyQt6>=6.9.1",
  "PyQt6-Qt6>=6.9.1",
  "pyqt6-utils>=0.5.0",
]
dev = [
  "black>=25.9.0",
  "mypy>=1.18.2",
  "pyqt6-stubs>=20250824",
  "types-requests>=2.32.4.20250913",
]
docs = [
  "sphinx>=8.0",
  "myst-parser>=4.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "mypy>=1.18.2",
    "pyqt6-stubs>=20250824",
    "types-requests>=2.32.4.20250913",
]

[tool.uv]
package = true


[tool.setuptools.package-data]
magboltz_gui = [
    "ui/*.ui",
    "database/*.csv",
    "icons/*.svg",
    "icons/*.png",
    "icons/macOS_icons/*.png",
    "icons/linux_icons/*.png",
    "icons/linux_icons/*.svg",
]

[tool.mypy]
strict = true
files = ["src"]
python_version = "3.12"

[[tool.mypy.overrides]]
module = ["PyQt6", "PyQt6.*"]
ignore_missing_imports = true

[tool.black]
line-length = 120
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | generated
)/
'''

[project.scripts]
magboltz-gui = "magboltz_gui.main:main"
gen-ui = "magboltz_gui.tool.gen_ui:main"

[project.urls]
Homepage = "https://gitlab.com/gasp-lab/magboltz-gui"
Documentation = "https://gitlab.com/gasp-lab/magboltz-gui/-/tree/master/docs"
Source = "https://gitlab.com/gasp-lab/magboltz-gui"
Tracker = "https://gitlab.com/gasp-lab/magboltz-gui/issues"
